package net.sf.perftence.fluent;

/**
 * An invocation overrides execute and defines behaviour of an invocation in
 * there.
 */
public abstract class Invocation implements Runnable {

    /**
     * Override this to define the test
     */
    public abstract void execute();

    /**
     * Run the invocation in an environment where we can handle the exceptions
     * generated by the test method.
     */
    @Override
    public void run() {
        // try {
        execute();
        // } catch (Throwable t) /*
        // * Any other exception we handle and then we
        // * interrupt the other threads.
        // */{
        // handleException(t);
        // interruptThreads();
        // }
    }

    protected abstract void interruptThreads();

    protected abstract void handleException(Throwable t);

}
