package net.sf.perftence.backlog;

import net.sf.simplebacklog.AbstractBacklogging;
import net.sf.simplebacklog.Backlog;
import net.sf.simplebacklog.BacklogFactory;

public class PerftenceBacklog extends AbstractBacklogging {
    private final BacklogFactory backlogFactory;

    public PerftenceBacklog(final BacklogFactory factory) {
        this.backlogFactory = factory;
    }

    public void show() {
        backlog()
                .title("Backlog for pertence test tool:")
                .done("DONE:")
                .tasks(done(
                        "created mainentrypoint-example project with source example",
                        PerftenceTaskTag.developmentSupport),
                        done("add eclipse formatter settings under build project",
                                PerftenceTaskTag.ide),
                        done("additional build scripts for source jars",
                                PerftenceTaskTag.developmentSupport),
                        done("additional build scripts for distribution",
                                PerftenceTaskTag.developmentSupport),
                        done("publish to sourceforge",
                                PerftenceTaskTag.development),
                        done("rename TPS -> throughput",
                                PerftenceTaskTag.refactoring),
                        done("provide fluent based test examples with sources",
                                PerftenceTaskTag.developmentSupport),
                        done("provide agent based test examples with sources",
                                PerftenceTaskTag.developmentSupport),
                        done("provide distribution for test examples with sources",
                                PerftenceTaskTag.developmentSupport),
                        done("fix the source packages for 3rd party libs",
                                PerftenceTaskTag.developmentSupport),
                        done("removed unnecessary jars from the distribution packages",
                                PerftenceTaskTag.developmentSupport),
                        done("last second statistics for agent based tests",
                                PerftenceTaskTag.feature),
                        done("removed custom intermediate summary redundancy from intermediate summary builders",
                                PerftenceTaskTag.refactoring),
                        done("created perftence-junit-utils and responsecode-summaryappender projects",
                                PerftenceTaskTag.refactoring),
                        done("added some unit tests for the obvious ones",
                                PerftenceTaskTag.development),
                        done("distribution package for sourceforge",
                                PerftenceTaskTag.developmentSupport),
                        done("last second throughput graph for fluent based tests",
                                PerftenceTaskTag.feature),
                        done("added change log capabilities through svn diffing backlog",
                                PerftenceTaskTag.infrastructure),
                        done("added noInvocationGraph also for agent based test for overall statistics",
                                PerftenceTaskTag.feature),
                        done("enabled last second throughput graph writing also for agent based tests",
                                PerftenceTaskTag.feature),
                        done("agent based tests: category specific invocation reporters also respect noInvocationGraph() setting",
                                PerftenceTaskTag.feature),
                        done("agent based tests: optimize graph, no same graphs from overall to  category specific reports",
                                PerftenceTaskTag.feature),
                        done("agent based tests: Ability to turn off 'threads running current tasks' and task schedule differencies' measurements",
                                PerftenceTaskTag.feature),
                        done("acceptance-tests are also run when making a distribution package",
                                PerftenceTaskTag.deployment),
                        done("XYSeriesFactory in use, gave up using autoSort on XySeries",
                                PerftenceTaskTag.feature),
                        done("use emma to figure out where to put some more unit tests",
                                PerftenceTaskTag.codeQuality),
                        done("provided unit test for AdjustedFieldBuilder",
                                PerftenceTaskTag.codeQuality),
                        done("put perftence-bag into use all over the perftence",
                                PerftenceTaskTag.refactoring),
                        done("introduced perftence-junit module",
                                PerftenceTaskTag.refactoring),
                        done("empty unit test for Statistics",
                                PerftenceTaskTag.codeQuality),
                        done("first version of failures over test time -graph",
                                PerftenceTaskTag.feature),
                        done("last second throudisplayghput graph for agent based tests",
                                PerftenceTaskTag.feature),
                        done("new line-reader project",
                                PerftenceTaskTag.development),
                        done("provide line-reader project in distribution package",
                                PerftenceTaskTag.development),
                        done("write unit tests for summary fields",
                                PerftenceTaskTag.codeQuality),
                        done("introduced perftence-api module",
                                PerftenceTaskTag.developmentSupport),
                        done("added perftence-api module to the continous and distribution builds",
                                PerftenceTaskTag.deployment),
                        done("removed runtime junit dependency from perftence, use it only as testCompile",
                                PerftenceTaskTag.deployment),
                        done("added dependency analysis with tattletale",
                                PerftenceTaskTag.codeQuality),
                        done("introduced perftence-fileutil module",
                                PerftenceTaskTag.refactoring),
                        done("added perftence-fileutil to the continous and distribution builds",
                                PerftenceTaskTag.refactoring),
                        done("provided unit tests for junit-utils module",
                                PerftenceTaskTag.codeQuality),
                        done("provided unit tests for classhelper module",
                                PerftenceTaskTag.codeQuality),
                        done("provided more unit tests for LatencyProvider",
                                PerftenceTaskTag.codeQuality),
                        done("removed static evil for EstimatedInvocations ",
                                PerftenceTaskTag.refactoring),
                        done("unit tests for PerformanceTestSetupPojo.noSetup()",
                                PerftenceTaskTag.codeQuality),
                        done("breakup stuff from build.gradle into separate .gradle files, e.g. libproject.gradle has only lib file repo",
                                PerftenceTaskTag.build),
                        done("simplified thread run engine for finding out threading issues, perftence-concurrent provides this now",
                                PerftenceTaskTag.feature),
                        done("fixed dist task, dist package didn't contain all zips",
                                PerftenceTaskTag.build),
                        done("gradle continousBuild", PerftenceTaskTag.build),
                        done("gradle aggregateReports", PerftenceTaskTag.build),
                        done("gradle distributionPackage",
                                PerftenceTaskTag.build),
                        done("gradle main/testCodeAnalysis",
                                PerftenceTaskTag.build),
                        done("gradle buildEclipseSettings",
                                PerftenceTaskTag.build),
                        done("gradle newJavaProject", PerftenceTaskTag.build),
                        done("gradle newJavaLibProject", PerftenceTaskTag.build),
                        done("gradle svnRevision,svnStatus",
                                PerftenceTaskTag.build),
                        done("gradle backlog:showBacklog",
                                PerftenceTaskTag.build),
                        done("gradle backlog:hereIsSomethingTodo",
                                PerftenceTaskTag.build),
                        done("gradle backlog:featuresWaiting",
                                PerftenceTaskTag.build),
                        done("gradle svnfeaturesWaiting",
                                PerftenceTaskTag.build),
                        done("gradle backlog:featuresWaiting",
                                PerftenceTaskTag.build),
                        done("gradle addNewFilesToSvn,listFilesNotAddedToSvn",
                                PerftenceTaskTag.build),
                        done("gradle printChangeLog", PerftenceTaskTag.build),
                        done("gradle exportChangeLog", PerftenceTaskTag.build),
                        done("threadengine-api-example module",
                                PerftenceTaskTag.developmentSupport),
                        done("gradle testCodeDist,testCodeRelease",
                                PerftenceTaskTag.developmentSupport),
                        done("added median check for PerformanceRequirements",
                                PerftenceTaskTag.feature),
                        done("gradle createChangeLogScript",
                                PerftenceTaskTag.build),
                        done("fixed gradle aggregateFindBugsReport auxclasspath",
                                PerftenceTaskTag.build),
                        done("gradle emma output test coverage after the tests",
                                PerftenceTaskTag.build),
                        done("gradle continousBuildWithoutAcceptanceTests",
                                PerftenceTaskTag.build),
                        done("backlog/build.gradle cleanup",
                                PerftenceTaskTag.build),
                        done("new typeof gradle exportChangeLog",
                                PerftenceTaskTag.build),
                        done("java based backlogging", PerftenceTaskTag.backlog),
                        done("simple-backlog module", PerftenceTaskTag.backlog))

                .inProgress("IN PROGRESS:")
                .noTasks()

                .waiting("WAITING:")
                .tasks(waiting("failures over test time, use DateAxis",
                        PerftenceTaskTag.feature),
                        waiting("provide success rate percentage for intermediate statistics",
                                PerftenceTaskTag.feature),
                        waiting("provide unit test for WritingFileFailed and other failure cases",
                                PerftenceTaskTag.codeQuality),
                        waiting("provide tools to create ResponseCodesPerSecond graph, see http://code.google.com/p/jmeter-plugins/wiki/ResponseCodesPerSecond for example",
                                PerftenceTaskTag.feature),
                        waiting("split fluent and agent stuff into separate projects",
                                PerftenceTaskTag.refactoring),
                        waiting("provide means to create test results in an intermediate format",
                                PerftenceTaskTag.feature),
                        waiting("provide means to create test report from an intermediate format",
                                PerftenceTaskTag.feature),
                        waiting("provide means to define also Throwable/Error with allow() mechanism",
                                PerftenceTaskTag.feature),
                        waiting("provide means to tell the Executable  also Throwable/Error with allow() mechanism",
                                PerftenceTaskTag.feature),
                        waiting("upload test example distribution packages to project files (i.e. to source forge)",
                                PerftenceTaskTag.developmentSupport),
                        waiting("one intermediate summary statistics appender",
                                PerftenceTaskTag.refactoring),
                        waiting("latency frequencies -> ability to set the range for the graph e.g. using 99% percentile",
                                PerftenceTaskTag.feature),
                        waiting("statistics enhancement: define a latency rate",
                                PerftenceTaskTag.feature),
                        waiting("statistics enhancement: print out statistics for latencies over the defined rate i.e. statistics over statistics",
                                PerftenceTaskTag.feature),
                        waiting("study changing public interface DatasetAdapter GRAPHDATA to DatasetAdapter GRAPHDATA, CATEGORY",
                                PerftenceTaskTag.refactoring),
                        waiting("ability to define the TPS is used defining it before running the test, e.g. running at 500 TPS max when the test is running",
                                PerftenceTaskTag.feature))

                .show();
    }

    @Override
    protected Backlog backlog() {
        return this.backlogFactory.newBacklog();
    }
}
